### ISSUE TITLE
Braintree API configuration should be changeable in the UI

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/BraintreeWrapper#15]
The Braintree API config should be stored in the database and displayed as a form in Launcher's Settings page.

Search for 'Settings area' on http://starcounter.io/guides/web/launcher/ to learn how to do this.

**Comment by jakubklekota** [comment]
OK, it's done. Please check

**Comment by aloscha** [comment]
Fixed that, also upgrade with image for Braintree etc.

**Comment by warpech** [comment]
Closing as done
