### ISSUE TITLE
Is it worth maintaining this app?

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/BraintreeWrapper#33]
As seen in the issues of this app, nothing has been done to make this app work properly in a long time. That is problematic. The app itself was built in 2015 and has basically been in constant need of maintenance since that. 

I'm wondering whether this app is used anywhere and if it's worth to make it work again? Especially considering the time it would take to fix. I don't think the current issues adequately reflects the amount of work required to make this app useful. 

I would suggest decoupling this app from WebShop https://github.com/StarcounterApps/WebShop/issues/29 and deleting it together with [PaymentHistory](https://github.com/StarcounterApps/PaymentHistory) which only exists for this app.

CC @warpech

**Comment by warpech** [comment]
This app is crucial because it is the closest thing to credit card payment app that we need. It needs maintainance, but in order of importance.

**Comment by Mackiovello** [comment]
Got it. Then I'll fix #31 and #32 so that I can add the correct contributing instructions.
